import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/client";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { SignInButton } from "../src/components/SignInOutButton/SignInButton";
import { Pokedex } from "../src/components/Pokedex/Pokedex";
import Spinner from "react-spinner-material";
import pokemonLogo from "../public/pokemonLogo.png";

export default function Home() {
  const [session, loading] = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={pokemonLogo} alt="Pokemon Logo" />

        {session && (
          <>
            <Pokedex />
          </>
        )}
        <SignInButton />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
